baseURL = "https://multiverso.do"
languageCode = "es-do"
DefaultContentLanguage = "es"
title = "Multiverso Académico"
theme = "PaperMod"
enableGitInfo = true


# Versión de Hugo v0.160.1
pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "G-1RKT2C1BY5"

[Params]
    env = "production" # to enable google analytics, images optimization, etc.
    title = "Multiverso Académico"
    description = "Reflexiones sobre Ciencia, Educación y Gestión Universitaria"
    keywords = ["UASD", "Ciencia", "Educación", "Gestión Universitaria", "Física"]
    author = "Vladimir Pérez"
    # Estética
    defaultTheme = "auto" # dark, light, auto
    disableThemeToggle = false
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemenu = false
    showtoc = true
    tocopen = true

    [Params.assets]
        favicon = "img/logo.png"
        favicon16x16 = "img/logo.png"
        favicon32x32 = "img/logo.png"
        apple_touch_icon = "img/logo.png"
        safari_pinned_tab = "img/logo.png"

    [Params.label]
        text = "Multiverso Académico"
        icon = "img/logo.png"
        iconHeight = 35

    [Params.profileMode]
        enabled = true # needs to be true for the card-like home page
        title = "Multiverso Académico"
        subtitle = "<div class='profile-slogan'>Reflexiones sobre Ciencia, Educación y Gestión Universitaria</div><div class='profile-description'><strong>¡Bienvenidos a Multiverso Académico!</strong> Este blog es un espacio dedicado a la reflexión y el análisis sobre Ciencia, Tecnología, Educación y Gestión Universitaria. Aquí encontrarás artículos que exploran ideas innovadoras y prácticas actuales en investigación científica, políticas educativas y administración académica. Esperamos que disfrutes de la lectura y te unas a las discusiones, contribuyendo con tus propias perspectivas y experiencias.</div>"
        imageUrl = "img/logo.png"
        imageWidth = 120
        imageHeight = 120
        imageTitle = "Vladimir Pérez"
        [[Params.profileMode.buttons]]
            name = "Explorar Artículos"
            url = "post"
        [[Params.profileMode.buttons]]
            name = "Sobre este blog"
            url = "page/about/"

    [Params.homeInfoParams]
        Title = ""
        Content = ""

    [[Params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/vladimirck"
    [[Params.socialIcons]]
        name = "github"
        url = "https://github.com/vladimirck"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Artículos"
        url = "/post/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Etiquetas"
        url = "/tags/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "Sobre mí"
        url = "/page/about/"
        weight = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # Permitir HTML en los posts
    [markup.highlight]
        noClasses = false
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
