baseurl = "https://username.github.io"
LanguageCode = "es-DO"
DefaultContentLanguage = "es"

title = "Multiverso Académico"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  #homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Reflexiones sobre Ciencia, Educación y Gestión Universitaria"
  mainSections = ["post"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "02/01/2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  math = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Vladimir Pérez"
  website ="vladimir.do"
  email = "vladimirck@gmail.com"
# facebook = "username"
  github = "vladimirck"
# gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  medium = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"

[[menu.main]]
    name = "Inicio"
    url = ""
    weight = 1

[[menu.main]]
    name = "Temas"
    url = "tags/"
    weight = 2

[[menu.main]]
    name = "Acerca de mí"
    url = "page/about/"
    weight = 3

[taxonomies]
  tag = 'tags'

#En esta sección vamos a habilitar la capacidad de poder escribir expresiones matemáticas usando expresiones de Latex
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'],  ['$', '$']]
