baseURL = "https://multiverso.do"
languageCode = "es-do"
DefaultContentLanguage = "es"
title = "Multiverso Académico"
theme = "PaperMod"

# Versión de Hugo v0.160.1
pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "G-1RKT2C1BY5"

[Params]
    env = "production" # to enable google analytics, images optimization, etc.
    title = "Multiverso Académico"
    description = "Reflexiones sobre Ciencia, Educación y Gestión Universitaria"
    keywords = ["UASD", "Ciencia", "Educación", "Gestión Universitaria", "Física"]
    author = "Vladimir Pérez"
    # Estética
    defaultTheme = "auto" # dark, light, auto
    disableThemeToggle = false
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemenu = false
    showtoc = true
    tocopen = true

    [Params.label]
        text = "Multiverso Académico"
        icon = "img/logo.png"
        iconHeight = 35

    [Params.profileMode]
        enabled = true # needs to be true for the card-like home page
        title = "Multiverso Académico"
        subtitle = "Reflexiones sobre Ciencia, Educación y Gestión Universitaria"
        imageUrl = "img/logo.png"
        imageWidth = 120
        imageHeight = 120
        imageTitle = "Vladimir Pérez"
        [[Params.profileMode.buttons]]
            name = "Explorar Artículos"
            url = "post"
        [[Params.profileMode.buttons]]
            name = "Sobre este blog"
            url = "page/about/"

    [Params.homeInfoParams]
        Title = "Hola \U0001F44B"
        Content = "Bienvido a mi espacio de reflexiones. Aquí encontrarás artículos sobre la Universidad Autónoma de Santo Domingo (UASD), ciencia y pedagogía."

    [[Params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/vladimirck"
    [[Params.socialIcons]]
        name = "github"
        url = "https://github.com/vladimirck"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Artículos"
        url = "/post/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Etiquetas"
        url = "/tags/"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "Sobre mí"
        url = "/page/about/"
        weight = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # Permitir HTML en los posts
    [markup.highlight]
        noClasses = false